# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jpce/Projects/krakenapi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jpce/Projects/krakenapi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jpce/Projects/krakenapi/CMakeFiles /home/jpce/Projects/krakenapi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jpce/Projects/krakenapi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named krt

# Build rule for target.
krt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 krt
.PHONY : krt

# fast build rule for target.
krt/fast:
	$(MAKE) -f CMakeFiles/krt.dir/build.make CMakeFiles/krt.dir/build
.PHONY : krt/fast

#=============================================================================
# Target rules for targets named kapi

# Build rule for target.
kapi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kapi
.PHONY : kapi

# fast build rule for target.
kapi/fast:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/build
.PHONY : kapi/fast

#=============================================================================
# Target rules for targets named kpublic_test

# Build rule for target.
kpublic_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kpublic_test
.PHONY : kpublic_test

# fast build rule for target.
kpublic_test/fast:
	$(MAKE) -f CMakeFiles/kpublic_test.dir/build.make CMakeFiles/kpublic_test.dir/build
.PHONY : kpublic_test/fast

#=============================================================================
# Target rules for targets named libjson

# Build rule for target.
libjson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libjson
.PHONY : libjson

# fast build rule for target.
libjson/fast:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/build
.PHONY : libjson/fast

#=============================================================================
# Target rules for targets named kph

# Build rule for target.
kph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kph
.PHONY : kph

# fast build rule for target.
kph/fast:
	$(MAKE) -f CMakeFiles/kph.dir/build.make CMakeFiles/kph.dir/build
.PHONY : kph/fast

#=============================================================================
# Target rules for targets named kstatistics

# Build rule for target.
kstatistics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kstatistics
.PHONY : kstatistics

# fast build rule for target.
kstatistics/fast:
	$(MAKE) -f CMakeFiles/kstatistics.dir/build.make CMakeFiles/kstatistics.dir/build
.PHONY : kstatistics/fast

kph.o: kph.cpp.o

.PHONY : kph.o

# target to build an object file
kph.cpp.o:
	$(MAKE) -f CMakeFiles/kph.dir/build.make CMakeFiles/kph.dir/kph.cpp.o
.PHONY : kph.cpp.o

kph.i: kph.cpp.i

.PHONY : kph.i

# target to preprocess a source file
kph.cpp.i:
	$(MAKE) -f CMakeFiles/kph.dir/build.make CMakeFiles/kph.dir/kph.cpp.i
.PHONY : kph.cpp.i

kph.s: kph.cpp.s

.PHONY : kph.s

# target to generate assembly for a file
kph.cpp.s:
	$(MAKE) -f CMakeFiles/kph.dir/build.make CMakeFiles/kph.dir/kph.cpp.s
.PHONY : kph.cpp.s

kpublic_test.o: kpublic_test.cpp.o

.PHONY : kpublic_test.o

# target to build an object file
kpublic_test.cpp.o:
	$(MAKE) -f CMakeFiles/kpublic_test.dir/build.make CMakeFiles/kpublic_test.dir/kpublic_test.cpp.o
.PHONY : kpublic_test.cpp.o

kpublic_test.i: kpublic_test.cpp.i

.PHONY : kpublic_test.i

# target to preprocess a source file
kpublic_test.cpp.i:
	$(MAKE) -f CMakeFiles/kpublic_test.dir/build.make CMakeFiles/kpublic_test.dir/kpublic_test.cpp.i
.PHONY : kpublic_test.cpp.i

kpublic_test.s: kpublic_test.cpp.s

.PHONY : kpublic_test.s

# target to generate assembly for a file
kpublic_test.cpp.s:
	$(MAKE) -f CMakeFiles/kpublic_test.dir/build.make CMakeFiles/kpublic_test.dir/kpublic_test.cpp.s
.PHONY : kpublic_test.cpp.s

kraken/kassets.o: kraken/kassets.cpp.o

.PHONY : kraken/kassets.o

# target to build an object file
kraken/kassets.cpp.o:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kassets.cpp.o
.PHONY : kraken/kassets.cpp.o

kraken/kassets.i: kraken/kassets.cpp.i

.PHONY : kraken/kassets.i

# target to preprocess a source file
kraken/kassets.cpp.i:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kassets.cpp.i
.PHONY : kraken/kassets.cpp.i

kraken/kassets.s: kraken/kassets.cpp.s

.PHONY : kraken/kassets.s

# target to generate assembly for a file
kraken/kassets.cpp.s:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kassets.cpp.s
.PHONY : kraken/kassets.cpp.s

kraken/kclient.o: kraken/kclient.cpp.o

.PHONY : kraken/kclient.o

# target to build an object file
kraken/kclient.cpp.o:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kclient.cpp.o
.PHONY : kraken/kclient.cpp.o

kraken/kclient.i: kraken/kclient.cpp.i

.PHONY : kraken/kclient.i

# target to preprocess a source file
kraken/kclient.cpp.i:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kclient.cpp.i
.PHONY : kraken/kclient.cpp.i

kraken/kclient.s: kraken/kclient.cpp.s

.PHONY : kraken/kclient.s

# target to generate assembly for a file
kraken/kclient.cpp.s:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kclient.cpp.s
.PHONY : kraken/kclient.cpp.s

kraken/kohlc.o: kraken/kohlc.cpp.o

.PHONY : kraken/kohlc.o

# target to build an object file
kraken/kohlc.cpp.o:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kohlc.cpp.o
	$(MAKE) -f CMakeFiles/kpublic_test.dir/build.make CMakeFiles/kpublic_test.dir/kraken/kohlc.cpp.o
	$(MAKE) -f CMakeFiles/kstatistics.dir/build.make CMakeFiles/kstatistics.dir/kraken/kohlc.cpp.o
.PHONY : kraken/kohlc.cpp.o

kraken/kohlc.i: kraken/kohlc.cpp.i

.PHONY : kraken/kohlc.i

# target to preprocess a source file
kraken/kohlc.cpp.i:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kohlc.cpp.i
	$(MAKE) -f CMakeFiles/kpublic_test.dir/build.make CMakeFiles/kpublic_test.dir/kraken/kohlc.cpp.i
	$(MAKE) -f CMakeFiles/kstatistics.dir/build.make CMakeFiles/kstatistics.dir/kraken/kohlc.cpp.i
.PHONY : kraken/kohlc.cpp.i

kraken/kohlc.s: kraken/kohlc.cpp.s

.PHONY : kraken/kohlc.s

# target to generate assembly for a file
kraken/kohlc.cpp.s:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kohlc.cpp.s
	$(MAKE) -f CMakeFiles/kpublic_test.dir/build.make CMakeFiles/kpublic_test.dir/kraken/kohlc.cpp.s
	$(MAKE) -f CMakeFiles/kstatistics.dir/build.make CMakeFiles/kstatistics.dir/kraken/kohlc.cpp.s
.PHONY : kraken/kohlc.cpp.s

kraken/korder.o: kraken/korder.cpp.o

.PHONY : kraken/korder.o

# target to build an object file
kraken/korder.cpp.o:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/korder.cpp.o
.PHONY : kraken/korder.cpp.o

kraken/korder.i: kraken/korder.cpp.i

.PHONY : kraken/korder.i

# target to preprocess a source file
kraken/korder.cpp.i:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/korder.cpp.i
.PHONY : kraken/korder.cpp.i

kraken/korder.s: kraken/korder.cpp.s

.PHONY : kraken/korder.s

# target to generate assembly for a file
kraken/korder.cpp.s:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/korder.cpp.s
.PHONY : kraken/korder.cpp.s

kraken/korderbook.o: kraken/korderbook.cpp.o

.PHONY : kraken/korderbook.o

# target to build an object file
kraken/korderbook.cpp.o:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/korderbook.cpp.o
.PHONY : kraken/korderbook.cpp.o

kraken/korderbook.i: kraken/korderbook.cpp.i

.PHONY : kraken/korderbook.i

# target to preprocess a source file
kraken/korderbook.cpp.i:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/korderbook.cpp.i
.PHONY : kraken/korderbook.cpp.i

kraken/korderbook.s: kraken/korderbook.cpp.s

.PHONY : kraken/korderbook.s

# target to generate assembly for a file
kraken/korderbook.cpp.s:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/korderbook.cpp.s
.PHONY : kraken/korderbook.cpp.s

kraken/kplot.o: kraken/kplot.cpp.o

.PHONY : kraken/kplot.o

# target to build an object file
kraken/kplot.cpp.o:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kplot.cpp.o
.PHONY : kraken/kplot.cpp.o

kraken/kplot.i: kraken/kplot.cpp.i

.PHONY : kraken/kplot.i

# target to preprocess a source file
kraken/kplot.cpp.i:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kplot.cpp.i
.PHONY : kraken/kplot.cpp.i

kraken/kplot.s: kraken/kplot.cpp.s

.PHONY : kraken/kplot.s

# target to generate assembly for a file
kraken/kplot.cpp.s:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kplot.cpp.s
.PHONY : kraken/kplot.cpp.s

kraken/kspread.o: kraken/kspread.cpp.o

.PHONY : kraken/kspread.o

# target to build an object file
kraken/kspread.cpp.o:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kspread.cpp.o
.PHONY : kraken/kspread.cpp.o

kraken/kspread.i: kraken/kspread.cpp.i

.PHONY : kraken/kspread.i

# target to preprocess a source file
kraken/kspread.cpp.i:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kspread.cpp.i
.PHONY : kraken/kspread.cpp.i

kraken/kspread.s: kraken/kspread.cpp.s

.PHONY : kraken/kspread.s

# target to generate assembly for a file
kraken/kspread.cpp.s:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/kspread.cpp.s
.PHONY : kraken/kspread.cpp.s

kraken/ktrade.o: kraken/ktrade.cpp.o

.PHONY : kraken/ktrade.o

# target to build an object file
kraken/ktrade.cpp.o:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/ktrade.cpp.o
.PHONY : kraken/ktrade.cpp.o

kraken/ktrade.i: kraken/ktrade.cpp.i

.PHONY : kraken/ktrade.i

# target to preprocess a source file
kraken/ktrade.cpp.i:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/ktrade.cpp.i
.PHONY : kraken/ktrade.cpp.i

kraken/ktrade.s: kraken/ktrade.cpp.s

.PHONY : kraken/ktrade.s

# target to generate assembly for a file
kraken/ktrade.cpp.s:
	$(MAKE) -f CMakeFiles/kapi.dir/build.make CMakeFiles/kapi.dir/kraken/ktrade.cpp.s
.PHONY : kraken/ktrade.cpp.s

krt.o: krt.cpp.o

.PHONY : krt.o

# target to build an object file
krt.cpp.o:
	$(MAKE) -f CMakeFiles/krt.dir/build.make CMakeFiles/krt.dir/krt.cpp.o
.PHONY : krt.cpp.o

krt.i: krt.cpp.i

.PHONY : krt.i

# target to preprocess a source file
krt.cpp.i:
	$(MAKE) -f CMakeFiles/krt.dir/build.make CMakeFiles/krt.dir/krt.cpp.i
.PHONY : krt.cpp.i

krt.s: krt.cpp.s

.PHONY : krt.s

# target to generate assembly for a file
krt.cpp.s:
	$(MAKE) -f CMakeFiles/krt.dir/build.make CMakeFiles/krt.dir/krt.cpp.s
.PHONY : krt.cpp.s

kstatistics.o: kstatistics.cpp.o

.PHONY : kstatistics.o

# target to build an object file
kstatistics.cpp.o:
	$(MAKE) -f CMakeFiles/kstatistics.dir/build.make CMakeFiles/kstatistics.dir/kstatistics.cpp.o
.PHONY : kstatistics.cpp.o

kstatistics.i: kstatistics.cpp.i

.PHONY : kstatistics.i

# target to preprocess a source file
kstatistics.cpp.i:
	$(MAKE) -f CMakeFiles/kstatistics.dir/build.make CMakeFiles/kstatistics.dir/kstatistics.cpp.i
.PHONY : kstatistics.cpp.i

kstatistics.s: kstatistics.cpp.s

.PHONY : kstatistics.s

# target to generate assembly for a file
kstatistics.cpp.s:
	$(MAKE) -f CMakeFiles/kstatistics.dir/build.make CMakeFiles/kstatistics.dir/kstatistics.cpp.s
.PHONY : kstatistics.cpp.s

libjson/_internal/Source/JSONAllocator.o: libjson/_internal/Source/JSONAllocator.cpp.o

.PHONY : libjson/_internal/Source/JSONAllocator.o

# target to build an object file
libjson/_internal/Source/JSONAllocator.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONAllocator.cpp.o
.PHONY : libjson/_internal/Source/JSONAllocator.cpp.o

libjson/_internal/Source/JSONAllocator.i: libjson/_internal/Source/JSONAllocator.cpp.i

.PHONY : libjson/_internal/Source/JSONAllocator.i

# target to preprocess a source file
libjson/_internal/Source/JSONAllocator.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONAllocator.cpp.i
.PHONY : libjson/_internal/Source/JSONAllocator.cpp.i

libjson/_internal/Source/JSONAllocator.s: libjson/_internal/Source/JSONAllocator.cpp.s

.PHONY : libjson/_internal/Source/JSONAllocator.s

# target to generate assembly for a file
libjson/_internal/Source/JSONAllocator.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONAllocator.cpp.s
.PHONY : libjson/_internal/Source/JSONAllocator.cpp.s

libjson/_internal/Source/JSONChildren.o: libjson/_internal/Source/JSONChildren.cpp.o

.PHONY : libjson/_internal/Source/JSONChildren.o

# target to build an object file
libjson/_internal/Source/JSONChildren.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONChildren.cpp.o
.PHONY : libjson/_internal/Source/JSONChildren.cpp.o

libjson/_internal/Source/JSONChildren.i: libjson/_internal/Source/JSONChildren.cpp.i

.PHONY : libjson/_internal/Source/JSONChildren.i

# target to preprocess a source file
libjson/_internal/Source/JSONChildren.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONChildren.cpp.i
.PHONY : libjson/_internal/Source/JSONChildren.cpp.i

libjson/_internal/Source/JSONChildren.s: libjson/_internal/Source/JSONChildren.cpp.s

.PHONY : libjson/_internal/Source/JSONChildren.s

# target to generate assembly for a file
libjson/_internal/Source/JSONChildren.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONChildren.cpp.s
.PHONY : libjson/_internal/Source/JSONChildren.cpp.s

libjson/_internal/Source/JSONDebug.o: libjson/_internal/Source/JSONDebug.cpp.o

.PHONY : libjson/_internal/Source/JSONDebug.o

# target to build an object file
libjson/_internal/Source/JSONDebug.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONDebug.cpp.o
.PHONY : libjson/_internal/Source/JSONDebug.cpp.o

libjson/_internal/Source/JSONDebug.i: libjson/_internal/Source/JSONDebug.cpp.i

.PHONY : libjson/_internal/Source/JSONDebug.i

# target to preprocess a source file
libjson/_internal/Source/JSONDebug.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONDebug.cpp.i
.PHONY : libjson/_internal/Source/JSONDebug.cpp.i

libjson/_internal/Source/JSONDebug.s: libjson/_internal/Source/JSONDebug.cpp.s

.PHONY : libjson/_internal/Source/JSONDebug.s

# target to generate assembly for a file
libjson/_internal/Source/JSONDebug.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONDebug.cpp.s
.PHONY : libjson/_internal/Source/JSONDebug.cpp.s

libjson/_internal/Source/JSONIterators.o: libjson/_internal/Source/JSONIterators.cpp.o

.PHONY : libjson/_internal/Source/JSONIterators.o

# target to build an object file
libjson/_internal/Source/JSONIterators.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONIterators.cpp.o
.PHONY : libjson/_internal/Source/JSONIterators.cpp.o

libjson/_internal/Source/JSONIterators.i: libjson/_internal/Source/JSONIterators.cpp.i

.PHONY : libjson/_internal/Source/JSONIterators.i

# target to preprocess a source file
libjson/_internal/Source/JSONIterators.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONIterators.cpp.i
.PHONY : libjson/_internal/Source/JSONIterators.cpp.i

libjson/_internal/Source/JSONIterators.s: libjson/_internal/Source/JSONIterators.cpp.s

.PHONY : libjson/_internal/Source/JSONIterators.s

# target to generate assembly for a file
libjson/_internal/Source/JSONIterators.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONIterators.cpp.s
.PHONY : libjson/_internal/Source/JSONIterators.cpp.s

libjson/_internal/Source/JSONMemory.o: libjson/_internal/Source/JSONMemory.cpp.o

.PHONY : libjson/_internal/Source/JSONMemory.o

# target to build an object file
libjson/_internal/Source/JSONMemory.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONMemory.cpp.o
.PHONY : libjson/_internal/Source/JSONMemory.cpp.o

libjson/_internal/Source/JSONMemory.i: libjson/_internal/Source/JSONMemory.cpp.i

.PHONY : libjson/_internal/Source/JSONMemory.i

# target to preprocess a source file
libjson/_internal/Source/JSONMemory.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONMemory.cpp.i
.PHONY : libjson/_internal/Source/JSONMemory.cpp.i

libjson/_internal/Source/JSONMemory.s: libjson/_internal/Source/JSONMemory.cpp.s

.PHONY : libjson/_internal/Source/JSONMemory.s

# target to generate assembly for a file
libjson/_internal/Source/JSONMemory.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONMemory.cpp.s
.PHONY : libjson/_internal/Source/JSONMemory.cpp.s

libjson/_internal/Source/JSONNode.o: libjson/_internal/Source/JSONNode.cpp.o

.PHONY : libjson/_internal/Source/JSONNode.o

# target to build an object file
libjson/_internal/Source/JSONNode.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONNode.cpp.o
.PHONY : libjson/_internal/Source/JSONNode.cpp.o

libjson/_internal/Source/JSONNode.i: libjson/_internal/Source/JSONNode.cpp.i

.PHONY : libjson/_internal/Source/JSONNode.i

# target to preprocess a source file
libjson/_internal/Source/JSONNode.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONNode.cpp.i
.PHONY : libjson/_internal/Source/JSONNode.cpp.i

libjson/_internal/Source/JSONNode.s: libjson/_internal/Source/JSONNode.cpp.s

.PHONY : libjson/_internal/Source/JSONNode.s

# target to generate assembly for a file
libjson/_internal/Source/JSONNode.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONNode.cpp.s
.PHONY : libjson/_internal/Source/JSONNode.cpp.s

libjson/_internal/Source/JSONNode_Mutex.o: libjson/_internal/Source/JSONNode_Mutex.cpp.o

.PHONY : libjson/_internal/Source/JSONNode_Mutex.o

# target to build an object file
libjson/_internal/Source/JSONNode_Mutex.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONNode_Mutex.cpp.o
.PHONY : libjson/_internal/Source/JSONNode_Mutex.cpp.o

libjson/_internal/Source/JSONNode_Mutex.i: libjson/_internal/Source/JSONNode_Mutex.cpp.i

.PHONY : libjson/_internal/Source/JSONNode_Mutex.i

# target to preprocess a source file
libjson/_internal/Source/JSONNode_Mutex.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONNode_Mutex.cpp.i
.PHONY : libjson/_internal/Source/JSONNode_Mutex.cpp.i

libjson/_internal/Source/JSONNode_Mutex.s: libjson/_internal/Source/JSONNode_Mutex.cpp.s

.PHONY : libjson/_internal/Source/JSONNode_Mutex.s

# target to generate assembly for a file
libjson/_internal/Source/JSONNode_Mutex.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONNode_Mutex.cpp.s
.PHONY : libjson/_internal/Source/JSONNode_Mutex.cpp.s

libjson/_internal/Source/JSONPreparse.o: libjson/_internal/Source/JSONPreparse.cpp.o

.PHONY : libjson/_internal/Source/JSONPreparse.o

# target to build an object file
libjson/_internal/Source/JSONPreparse.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONPreparse.cpp.o
.PHONY : libjson/_internal/Source/JSONPreparse.cpp.o

libjson/_internal/Source/JSONPreparse.i: libjson/_internal/Source/JSONPreparse.cpp.i

.PHONY : libjson/_internal/Source/JSONPreparse.i

# target to preprocess a source file
libjson/_internal/Source/JSONPreparse.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONPreparse.cpp.i
.PHONY : libjson/_internal/Source/JSONPreparse.cpp.i

libjson/_internal/Source/JSONPreparse.s: libjson/_internal/Source/JSONPreparse.cpp.s

.PHONY : libjson/_internal/Source/JSONPreparse.s

# target to generate assembly for a file
libjson/_internal/Source/JSONPreparse.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONPreparse.cpp.s
.PHONY : libjson/_internal/Source/JSONPreparse.cpp.s

libjson/_internal/Source/JSONStream.o: libjson/_internal/Source/JSONStream.cpp.o

.PHONY : libjson/_internal/Source/JSONStream.o

# target to build an object file
libjson/_internal/Source/JSONStream.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONStream.cpp.o
.PHONY : libjson/_internal/Source/JSONStream.cpp.o

libjson/_internal/Source/JSONStream.i: libjson/_internal/Source/JSONStream.cpp.i

.PHONY : libjson/_internal/Source/JSONStream.i

# target to preprocess a source file
libjson/_internal/Source/JSONStream.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONStream.cpp.i
.PHONY : libjson/_internal/Source/JSONStream.cpp.i

libjson/_internal/Source/JSONStream.s: libjson/_internal/Source/JSONStream.cpp.s

.PHONY : libjson/_internal/Source/JSONStream.s

# target to generate assembly for a file
libjson/_internal/Source/JSONStream.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONStream.cpp.s
.PHONY : libjson/_internal/Source/JSONStream.cpp.s

libjson/_internal/Source/JSONValidator.o: libjson/_internal/Source/JSONValidator.cpp.o

.PHONY : libjson/_internal/Source/JSONValidator.o

# target to build an object file
libjson/_internal/Source/JSONValidator.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONValidator.cpp.o
.PHONY : libjson/_internal/Source/JSONValidator.cpp.o

libjson/_internal/Source/JSONValidator.i: libjson/_internal/Source/JSONValidator.cpp.i

.PHONY : libjson/_internal/Source/JSONValidator.i

# target to preprocess a source file
libjson/_internal/Source/JSONValidator.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONValidator.cpp.i
.PHONY : libjson/_internal/Source/JSONValidator.cpp.i

libjson/_internal/Source/JSONValidator.s: libjson/_internal/Source/JSONValidator.cpp.s

.PHONY : libjson/_internal/Source/JSONValidator.s

# target to generate assembly for a file
libjson/_internal/Source/JSONValidator.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONValidator.cpp.s
.PHONY : libjson/_internal/Source/JSONValidator.cpp.s

libjson/_internal/Source/JSONWorker.o: libjson/_internal/Source/JSONWorker.cpp.o

.PHONY : libjson/_internal/Source/JSONWorker.o

# target to build an object file
libjson/_internal/Source/JSONWorker.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONWorker.cpp.o
.PHONY : libjson/_internal/Source/JSONWorker.cpp.o

libjson/_internal/Source/JSONWorker.i: libjson/_internal/Source/JSONWorker.cpp.i

.PHONY : libjson/_internal/Source/JSONWorker.i

# target to preprocess a source file
libjson/_internal/Source/JSONWorker.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONWorker.cpp.i
.PHONY : libjson/_internal/Source/JSONWorker.cpp.i

libjson/_internal/Source/JSONWorker.s: libjson/_internal/Source/JSONWorker.cpp.s

.PHONY : libjson/_internal/Source/JSONWorker.s

# target to generate assembly for a file
libjson/_internal/Source/JSONWorker.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONWorker.cpp.s
.PHONY : libjson/_internal/Source/JSONWorker.cpp.s

libjson/_internal/Source/JSONWriter.o: libjson/_internal/Source/JSONWriter.cpp.o

.PHONY : libjson/_internal/Source/JSONWriter.o

# target to build an object file
libjson/_internal/Source/JSONWriter.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONWriter.cpp.o
.PHONY : libjson/_internal/Source/JSONWriter.cpp.o

libjson/_internal/Source/JSONWriter.i: libjson/_internal/Source/JSONWriter.cpp.i

.PHONY : libjson/_internal/Source/JSONWriter.i

# target to preprocess a source file
libjson/_internal/Source/JSONWriter.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONWriter.cpp.i
.PHONY : libjson/_internal/Source/JSONWriter.cpp.i

libjson/_internal/Source/JSONWriter.s: libjson/_internal/Source/JSONWriter.cpp.s

.PHONY : libjson/_internal/Source/JSONWriter.s

# target to generate assembly for a file
libjson/_internal/Source/JSONWriter.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/JSONWriter.cpp.s
.PHONY : libjson/_internal/Source/JSONWriter.cpp.s

libjson/_internal/Source/internalJSONNode.o: libjson/_internal/Source/internalJSONNode.cpp.o

.PHONY : libjson/_internal/Source/internalJSONNode.o

# target to build an object file
libjson/_internal/Source/internalJSONNode.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/internalJSONNode.cpp.o
.PHONY : libjson/_internal/Source/internalJSONNode.cpp.o

libjson/_internal/Source/internalJSONNode.i: libjson/_internal/Source/internalJSONNode.cpp.i

.PHONY : libjson/_internal/Source/internalJSONNode.i

# target to preprocess a source file
libjson/_internal/Source/internalJSONNode.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/internalJSONNode.cpp.i
.PHONY : libjson/_internal/Source/internalJSONNode.cpp.i

libjson/_internal/Source/internalJSONNode.s: libjson/_internal/Source/internalJSONNode.cpp.s

.PHONY : libjson/_internal/Source/internalJSONNode.s

# target to generate assembly for a file
libjson/_internal/Source/internalJSONNode.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/internalJSONNode.cpp.s
.PHONY : libjson/_internal/Source/internalJSONNode.cpp.s

libjson/_internal/Source/libjson.o: libjson/_internal/Source/libjson.cpp.o

.PHONY : libjson/_internal/Source/libjson.o

# target to build an object file
libjson/_internal/Source/libjson.cpp.o:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/libjson.cpp.o
.PHONY : libjson/_internal/Source/libjson.cpp.o

libjson/_internal/Source/libjson.i: libjson/_internal/Source/libjson.cpp.i

.PHONY : libjson/_internal/Source/libjson.i

# target to preprocess a source file
libjson/_internal/Source/libjson.cpp.i:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/libjson.cpp.i
.PHONY : libjson/_internal/Source/libjson.cpp.i

libjson/_internal/Source/libjson.s: libjson/_internal/Source/libjson.cpp.s

.PHONY : libjson/_internal/Source/libjson.s

# target to generate assembly for a file
libjson/_internal/Source/libjson.cpp.s:
	$(MAKE) -f CMakeFiles/libjson.dir/build.make CMakeFiles/libjson.dir/libjson/_internal/Source/libjson.cpp.s
.PHONY : libjson/_internal/Source/libjson.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... krt"
	@echo "... edit_cache"
	@echo "... kapi"
	@echo "... kpublic_test"
	@echo "... libjson"
	@echo "... kph"
	@echo "... kstatistics"
	@echo "... kph.o"
	@echo "... kph.i"
	@echo "... kph.s"
	@echo "... kpublic_test.o"
	@echo "... kpublic_test.i"
	@echo "... kpublic_test.s"
	@echo "... kraken/kassets.o"
	@echo "... kraken/kassets.i"
	@echo "... kraken/kassets.s"
	@echo "... kraken/kclient.o"
	@echo "... kraken/kclient.i"
	@echo "... kraken/kclient.s"
	@echo "... kraken/kohlc.o"
	@echo "... kraken/kohlc.i"
	@echo "... kraken/kohlc.s"
	@echo "... kraken/korder.o"
	@echo "... kraken/korder.i"
	@echo "... kraken/korder.s"
	@echo "... kraken/korderbook.o"
	@echo "... kraken/korderbook.i"
	@echo "... kraken/korderbook.s"
	@echo "... kraken/kplot.o"
	@echo "... kraken/kplot.i"
	@echo "... kraken/kplot.s"
	@echo "... kraken/kspread.o"
	@echo "... kraken/kspread.i"
	@echo "... kraken/kspread.s"
	@echo "... kraken/ktrade.o"
	@echo "... kraken/ktrade.i"
	@echo "... kraken/ktrade.s"
	@echo "... krt.o"
	@echo "... krt.i"
	@echo "... krt.s"
	@echo "... kstatistics.o"
	@echo "... kstatistics.i"
	@echo "... kstatistics.s"
	@echo "... libjson/_internal/Source/JSONAllocator.o"
	@echo "... libjson/_internal/Source/JSONAllocator.i"
	@echo "... libjson/_internal/Source/JSONAllocator.s"
	@echo "... libjson/_internal/Source/JSONChildren.o"
	@echo "... libjson/_internal/Source/JSONChildren.i"
	@echo "... libjson/_internal/Source/JSONChildren.s"
	@echo "... libjson/_internal/Source/JSONDebug.o"
	@echo "... libjson/_internal/Source/JSONDebug.i"
	@echo "... libjson/_internal/Source/JSONDebug.s"
	@echo "... libjson/_internal/Source/JSONIterators.o"
	@echo "... libjson/_internal/Source/JSONIterators.i"
	@echo "... libjson/_internal/Source/JSONIterators.s"
	@echo "... libjson/_internal/Source/JSONMemory.o"
	@echo "... libjson/_internal/Source/JSONMemory.i"
	@echo "... libjson/_internal/Source/JSONMemory.s"
	@echo "... libjson/_internal/Source/JSONNode.o"
	@echo "... libjson/_internal/Source/JSONNode.i"
	@echo "... libjson/_internal/Source/JSONNode.s"
	@echo "... libjson/_internal/Source/JSONNode_Mutex.o"
	@echo "... libjson/_internal/Source/JSONNode_Mutex.i"
	@echo "... libjson/_internal/Source/JSONNode_Mutex.s"
	@echo "... libjson/_internal/Source/JSONPreparse.o"
	@echo "... libjson/_internal/Source/JSONPreparse.i"
	@echo "... libjson/_internal/Source/JSONPreparse.s"
	@echo "... libjson/_internal/Source/JSONStream.o"
	@echo "... libjson/_internal/Source/JSONStream.i"
	@echo "... libjson/_internal/Source/JSONStream.s"
	@echo "... libjson/_internal/Source/JSONValidator.o"
	@echo "... libjson/_internal/Source/JSONValidator.i"
	@echo "... libjson/_internal/Source/JSONValidator.s"
	@echo "... libjson/_internal/Source/JSONWorker.o"
	@echo "... libjson/_internal/Source/JSONWorker.i"
	@echo "... libjson/_internal/Source/JSONWorker.s"
	@echo "... libjson/_internal/Source/JSONWriter.o"
	@echo "... libjson/_internal/Source/JSONWriter.i"
	@echo "... libjson/_internal/Source/JSONWriter.s"
	@echo "... libjson/_internal/Source/internalJSONNode.o"
	@echo "... libjson/_internal/Source/internalJSONNode.i"
	@echo "... libjson/_internal/Source/internalJSONNode.s"
	@echo "... libjson/_internal/Source/libjson.o"
	@echo "... libjson/_internal/Source/libjson.i"
	@echo "... libjson/_internal/Source/libjson.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

